name: packer
on:
  pull_request:
jobs:
  pack:
   runs-on: ubuntu-22.04
   steps:
    - uses: actions/checkout@v3
      with:
        path: stu/
    - uses: actions/upload-artifact@v3
      with:
        name: stu-code
        path: stu/
